# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indent/v1/account_api.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'indent/v1/resources_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("indent/v1/account_api.proto", :syntax => :proto3) do
    add_message "indent.v1.ListSpacesRequest" do
      optional :parent, :string, 1, json_name: "parent"
      optional :page_size, :int32, 2, json_name: "pageSize"
    end
    add_message "indent.v1.ListSpacesResponse" do
      repeated :spaces, :message, 1, "indent.v1.Space", json_name: "spaces"
    end
    add_message "indent.v1.GetSpaceRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
    end
    add_message "indent.v1.CreateSpaceRequest" do
      optional :space, :message, 1, "indent.v1.Space", json_name: "space"
    end
    add_message "indent.v1.UpdateSpaceRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :space, :message, 2, "indent.v1.Space", json_name: "space"
    end
    add_message "indent.v1.DeleteSpaceRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :recursive, :bool, 2, json_name: "recursive"
    end
    add_message "indent.v1.Space" do
      optional :name, :string, 1, json_name: "name"
      optional :parent, :string, 2, json_name: "parent"
      optional :display_name, :string, 3, json_name: "displayName"
    end
    add_message "indent.v1.SetPolicyRequest" do
      optional :resource, :string, 1, json_name: "resource"
      optional :policy, :message, 2, "indent.v1.Policy", json_name: "policy"
    end
    add_message "indent.v1.GetPolicyRequest" do
      optional :resource, :string, 1, json_name: "resource"
    end
    add_message "indent.v1.Policy" do
      repeated :bindings, :message, 2, "indent.v1.Binding", json_name: "bindings"
    end
  end
end

module Indent
  module V1
    ListSpacesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListSpacesRequest").msgclass
    ListSpacesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListSpacesResponse").msgclass
    GetSpaceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetSpaceRequest").msgclass
    CreateSpaceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateSpaceRequest").msgclass
    UpdateSpaceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdateSpaceRequest").msgclass
    DeleteSpaceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteSpaceRequest").msgclass
    Space = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Space").msgclass
    SetPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.SetPolicyRequest").msgclass
    GetPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetPolicyRequest").msgclass
    Policy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Policy").msgclass
  end
end
