# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indent/v1/block_api.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'indent/v1/resources_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("indent/v1/block_api.proto", :syntax => :proto3) do
    add_message "indent.v1.ListBlocksRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :label_selector, :string, 2, json_name: "labelSelector"
      optional :latest, :bool, 3, json_name: "latest"
      repeated :among, :string, 4, json_name: "among"
      optional :page_size, :int32, 10, json_name: "pageSize"
      optional :page_token, :string, 11, json_name: "pageToken"
    end
    add_message "indent.v1.ListBlocksResponse" do
      repeated :blocks, :message, 1, "indent.v1.Block", json_name: "blocks"
      optional :next_page_token, :string, 2, json_name: "nextPageToken"
    end
    add_message "indent.v1.GetBlockRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :block_name, :string, 2, json_name: "blockName"
    end
    add_message "indent.v1.CreateBlockRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :ephemeral, :bool, 5, json_name: "ephemeral"
      optional :announce, :bool, 15, json_name: "announce"
      optional :block, :message, 40, "indent.v1.Block", json_name: "block"
    end
    add_message "indent.v1.UpdateBlockRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :block_name, :string, 3, json_name: "blockName"
      optional :ephemeral, :bool, 5, json_name: "ephemeral"
      optional :announce, :bool, 15, json_name: "announce"
      optional :block, :message, 40, "indent.v1.Block", json_name: "block"
    end
    add_message "indent.v1.DeleteBlockRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :block_name, :string, 2, json_name: "blockName"
    end
    add_message "indent.v1.BulkDeleteBlocksRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      repeated :block_names, :string, 40, json_name: "blockNames"
    end
    add_message "indent.v1.BulkDeleteBlocksResponse" do
    end
  end
end

module Indent
  module V1
    ListBlocksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListBlocksRequest").msgclass
    ListBlocksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListBlocksResponse").msgclass
    GetBlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetBlockRequest").msgclass
    CreateBlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateBlockRequest").msgclass
    UpdateBlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdateBlockRequest").msgclass
    DeleteBlockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteBlockRequest").msgclass
    BulkDeleteBlocksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.BulkDeleteBlocksRequest").msgclass
    BulkDeleteBlocksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.BulkDeleteBlocksResponse").msgclass
  end
end
