# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indent/v1/claim_api.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'indent/audit/v1/resources_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("indent/v1/claim_api.proto", :syntax => :proto3) do
    add_message "indent.v1.ListClaimsRequest" do
      optional :space_name, :string, 13, json_name: "spaceName"
      optional :label_selector, :string, 25, json_name: "labelSelector"
      optional :page_size, :int32, 50, json_name: "pageSize"
      optional :page_token, :string, 55, json_name: "pageToken"
    end
    add_message "indent.v1.ListClaimsResponse" do
      repeated :claims, :message, 1, "indent.audit.v1.Event", json_name: "claims"
      optional :next_page_token, :string, 2, json_name: "nextPageToken"
    end
    add_message "indent.v1.GetClaimRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :claim_name, :string, 2, json_name: "claimName"
    end
    add_message "indent.v1.CreateClaimRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :claim, :message, 40, "indent.audit.v1.Event", json_name: "claim"
    end
    add_message "indent.v1.RetractClaimRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :claim_name, :string, 2, json_name: "claimName"
    end
  end
end

module Indent
  module V1
    ListClaimsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListClaimsRequest").msgclass
    ListClaimsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListClaimsResponse").msgclass
    GetClaimRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetClaimRequest").msgclass
    CreateClaimRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateClaimRequest").msgclass
    RetractClaimRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.RetractClaimRequest").msgclass
  end
end
