# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: indent/v1/claim_api.proto for package 'indent.v1'
# Original file comments:
#
# Copyright 2019 Indent Inc
#
#

require 'grpc'
require 'indent/v1/claim_api_pb'

module Indent
  module V1
    module ClaimAPI
      # ClaimAPI is used to submit statements which are used to evaluate whether a Petition should be granted.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'indent.v1.ClaimAPI'

        # List the Claims in the given space.
        rpc :ListClaims, ::Indent::V1::ListClaimsRequest, ::Indent::V1::ListClaimsResponse
        # Retrieve specified Claim by name and space.
        rpc :GetClaim, ::Indent::V1::GetClaimRequest, ::Indent::Audit::V1::Event
        # Create a new Claim within a space.
        rpc :CreateClaim, ::Indent::V1::CreateClaimRequest, ::Indent::Audit::V1::Event
        # RetractClaim is used to invalidate a previously made Claim.
        rpc :RetractClaim, ::Indent::V1::RetractClaimRequest, ::Indent::Audit::V1::Event
      end

      Stub = Service.rpc_stub_class
    end
  end
end
