# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indent/v1/integration_api.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'indent/audit/v1/resources_pb'
require 'indent/log/log_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("indent/v1/integration_api.proto", :syntax => :proto3) do
    add_message "indent.v1.GroupVersionKind" do
      optional :group, :string, 1, json_name: "group"
      optional :version, :string, 2, json_name: "version"
      optional :kind, :string, 3, json_name: "kind"
    end
    add_message "indent.v1.Capabilities" do
      repeated :kinds, :message, 6, "indent.v1.GroupVersionKind", json_name: "kinds"
      repeated :capabilities, :string, 9, json_name: "capabilities"
    end
    add_message "indent.v1.Integration" do
      optional :meta, :message, 3, "indent.audit.v1.Meta", json_name: "meta"
      optional :capabilities, :message, 9, "indent.v1.Capabilities", json_name: "capabilities"
    end
    add_message "indent.v1.ListIntegrationsRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :label_selector, :string, 2, json_name: "labelSelector"
      repeated :kinds, :string, 4, json_name: "kinds"
      repeated :capabilities, :string, 7, json_name: "capabilities"
      optional :page_size, :int32, 10, json_name: "pageSize"
      optional :page_token, :string, 11, json_name: "pageToken"
    end
    add_message "indent.v1.ListIntegrationsResponse" do
      repeated :integrations, :message, 1, "indent.v1.Integration", json_name: "integrations"
      optional :next_page_token, :string, 2, json_name: "nextPageToken"
    end
    add_message "indent.v1.GetIntegrationRequest" do
      optional :space_name, :string, 5, json_name: "spaceName"
      optional :integration_name, :string, 9, json_name: "integrationName"
    end
    add_message "indent.v1.Install" do
      optional :meta, :message, 3, "indent.audit.v1.Meta", json_name: "meta"
      optional :integration, :message, 5, "indent.v1.Integration", json_name: "integration"
      optional :capabilities, :message, 7, "indent.v1.Capabilities", json_name: "capabilities"
      optional :disabled, :bool, 9, json_name: "disabled"
      optional :status, :enum, 15, "indent.v1.Install.Status", json_name: "status"
    end
    add_enum "indent.v1.Install.Status" do
      value :NotInstalled, 0
      value :Installed, 1
      value :ActionRequired, 2
    end
    add_message "indent.v1.ListInstallsRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :label_selector, :string, 2, json_name: "labelSelector"
      repeated :kinds, :string, 4, json_name: "kinds"
      repeated :capabilities, :string, 7, json_name: "capabilities"
      optional :page_size, :int32, 10, json_name: "pageSize"
      optional :page_token, :string, 11, json_name: "pageToken"
    end
    add_message "indent.v1.ListInstallsResponse" do
      repeated :installs, :message, 1, "indent.v1.Install", json_name: "installs"
      optional :next_page_token, :string, 2, json_name: "nextPageToken"
    end
    add_message "indent.v1.GetInstallRequest" do
      optional :space_name, :string, 5, json_name: "spaceName"
      optional :install_name, :string, 9, json_name: "installName"
    end
  end
end

module Indent
  module V1
    GroupVersionKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GroupVersionKind").msgclass
    Capabilities = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Capabilities").msgclass
    Integration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Integration").msgclass
    ListIntegrationsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListIntegrationsRequest").msgclass
    ListIntegrationsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListIntegrationsResponse").msgclass
    GetIntegrationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetIntegrationRequest").msgclass
    Install = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Install").msgclass
    Install::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Install.Status").enummodule
    ListInstallsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListInstallsRequest").msgclass
    ListInstallsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListInstallsResponse").msgclass
    GetInstallRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetInstallRequest").msgclass
  end
end
