# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: indent/v1/integration_api.proto for package 'indent.v1'
# Original file comments:
#
# Copyright 2022 Indent Inc
#
#

require 'grpc'
require 'indent/v1/integration_api_pb'

module Indent
  module V1
    module IntegrationAPI
      # Provides an abstraction for configuring how Indent connects and interacts with external systems.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'indent.v1.IntegrationAPI'

        # List Integrations available to be installed.
        rpc :ListIntegrations, ::Indent::V1::ListIntegrationsRequest, ::Indent::V1::ListIntegrationsResponse
        # Retrieve specified Integration by name and space.
        rpc :GetIntegration, ::Indent::V1::GetIntegrationRequest, ::Indent::V1::Integration
        # List Installs that have been added to the space.
        rpc :ListInstalls, ::Indent::V1::ListInstallsRequest, ::Indent::V1::ListInstallsResponse
        # Retrieve specified Install by name and space.
        rpc :GetInstall, ::Indent::V1::GetInstallRequest, ::Indent::V1::Install
      end

      Stub = Service.rpc_stub_class
    end
  end
end
