# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: indent/v1/petition_api.proto for package 'indent.v1'
# Original file comments:
#
# Copyright 2019 Indent Inc
#
#

require 'grpc'
require 'indent/v1/petition_api_pb'

module Indent
  module V1
    module PetitionAPI
      # Allows users to request access to resources and provide claims to approve access.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'indent.v1.PetitionAPI'

        # List the Petitions in the given space including ones that have been approved or withdrawn.
        rpc :ListPetitions, ::Indent::V1::ListPetitionsRequest, ::Indent::V1::ListPetitionsResponse
        # Retrieve specified Petition by name and space.
        rpc :GetPetition, ::Indent::V1::GetPetitionRequest, ::Indent::V1::Petition
        # Create a new Petition within a space requesting access to specified resources.
        rpc :CreatePetition, ::Indent::V1::CreatePetitionRequest, ::Indent::V1::Petition
        # UpdatePetition allows modification of the contents of a Petition.
        rpc :UpdatePetition, ::Indent::V1::UpdatePetitionRequest, ::Indent::V1::Petition
        # Permanently destroy a Petition.
        rpc :DeletePetition, ::Indent::V1::DeletePetitionRequest, ::Indent::V1::Petition
        # StartPetition allows creating petitions using tokens with minimal access and without knowing which space.
        # This functionality should generally be reserved for external applications calling into Indent.
        rpc :StartPetition, ::Indent::V1::StartPetitionRequest, ::Indent::V1::Petition
        # List the Claims in the given petition in a space.
        rpc :ListClaims, ::Indent::V1::ListPetitionClaimsRequest, ::Indent::V1::ListPetitionClaimsResponse
        # Retrieve specified Claim by name and space.
        rpc :GetClaim, ::Indent::V1::GetPetitionClaimRequest, ::Indent::Audit::V1::Event
        # Create a new Claim for a Petition.
        rpc :CreateClaim, ::Indent::V1::CreatePetitionClaimRequest, ::Indent::Audit::V1::Event
      end

      Stub = Service.rpc_stub_class
    end
  end
end
