# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: indent/v1/provider_api.proto for package 'indent.v1'
# Original file comments:
#
# Copyright 2019 Indent Inc
#
#

require 'grpc'
require 'indent/v1/provider_api_pb'

module Indent
  module V1
    module ProviderAPI
      # Manages the configuration of providers including their credentials.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'indent.v1.ProviderAPI'

        # List the Providers in a given Space.
        rpc :ListProviders, ::Indent::V1::ListProvidersRequest, ::Indent::V1::ListProvidersResponse
        # Retrieve specified Provider by name.
        rpc :GetProvider, ::Indent::V1::GetProviderRequest, ::Indent::V1::Provider
        # Create a new Provider in given Space.
        rpc :CreateProvider, ::Indent::V1::CreateProviderRequest, ::Indent::V1::Provider
        # Update configuration of a Provider.
        rpc :UpdateProvider, ::Indent::V1::UpdateProviderRequest, ::Indent::V1::Provider
        # Delete a Provider.
        rpc :DeleteProvider, ::Indent::V1::DeleteProviderRequest, ::Indent::V1::Provider
        # List all inputs for a Provider.
        rpc :ListInputs, ::Indent::V1::ListInputsRequest, ::Indent::V1::ListInputsResponse
        # Get a specific input.
        rpc :GetInput, ::Indent::V1::GetInputRequest, ::Indent::V1::Input
        # Create an Input within a Provider.
        rpc :CreateInput, ::Indent::V1::CreateInputRequest, ::Indent::V1::Input
        # Update configuration of an Input.
        rpc :UpdateInput, ::Indent::V1::UpdateInputRequest, ::Indent::V1::Input
        # Delete an Input.
        rpc :DeleteInput, ::Indent::V1::DeleteInputRequest, ::Indent::V1::Input
        # List all outputs for a Provider.
        rpc :ListOutputs, ::Indent::V1::ListOutputsRequest, ::Indent::V1::ListOutputsResponse
        # Get a specific output.
        rpc :GetOutput, ::Indent::V1::GetOutputRequest, ::Indent::V1::Output
        # Create an Output within a Provider.
        rpc :CreateOutput, ::Indent::V1::CreateOutputRequest, ::Indent::V1::Output
        # Update configuration of an Output.
        rpc :UpdateOutput, ::Indent::V1::UpdateOutputRequest, ::Indent::V1::Output
        # Delete an Output.
        rpc :DeleteOutput, ::Indent::V1::DeleteOutputRequest, ::Indent::V1::Output
        # ListCredentials available for a given provider.
        rpc :ListCredentials, ::Indent::V1::ListCredentialsRequest, ::Indent::V1::ListCredentialsResponse
        # CreateCredential under given provider.
        rpc :CreateCredential, ::Indent::V1::CreateCredentialRequest, ::Indent::V1::Credential
        # DeleteCredential from provider.
        rpc :DeleteCredential, ::Indent::V1::DeleteCredentialRequest, ::Google::Protobuf::Empty
      end

      Stub = Service.rpc_stub_class
    end
  end
end
