# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indent/v1/provider_api.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/empty_pb'
require 'indent/v1/resources_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("indent/v1/provider_api.proto", :syntax => :proto3) do
    add_message "indent.v1.ListProvidersRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :page_size, :int32, 2, json_name: "pageSize"
    end
    add_message "indent.v1.ListProvidersResponse" do
      repeated :providers, :message, 1, "indent.v1.Provider", json_name: "providers"
    end
    add_message "indent.v1.GetProviderRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
    end
    add_message "indent.v1.CreateProviderRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider, :message, 2, "indent.v1.Provider", json_name: "provider"
    end
    add_message "indent.v1.UpdateProviderRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :provider, :message, 3, "indent.v1.Provider", json_name: "provider"
    end
    add_message "indent.v1.DeleteProviderRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
    end
    add_message "indent.v1.Provider" do
      optional :name, :string, 1, json_name: "name"
      optional :display_name, :string, 2, json_name: "displayName"
      optional :blob_location, :string, 3, json_name: "blobLocation"
    end
    add_message "indent.v1.ListInputsRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :page_size, :int32, 3, json_name: "pageSize"
    end
    add_message "indent.v1.ListInputsResponse" do
      repeated :inputs, :message, 1, "indent.v1.Input", json_name: "inputs"
    end
    add_message "indent.v1.GetInputRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :input_name, :string, 3, json_name: "inputName"
    end
    add_message "indent.v1.CreateInputRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :input, :message, 3, "indent.v1.Input", json_name: "input"
    end
    add_message "indent.v1.UpdateInputRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :input_name, :string, 3, json_name: "inputName"
      optional :input, :message, 4, "indent.v1.Input", json_name: "input"
    end
    add_message "indent.v1.DeleteInputRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :input_name, :string, 3, json_name: "inputName"
    end
    add_message "indent.v1.Input" do
      optional :name, :string, 1, json_name: "name"
      optional :display_name, :string, 2, json_name: "displayName"
      optional :schema, :message, 3, "indent.v1.Schema", json_name: "schema"
      repeated :steps, :message, 4, "indent.v1.TransformStep", json_name: "steps"
      optional :storage, :message, 5, "indent.v1.Storage", json_name: "storage"
    end
    add_message "indent.v1.ListOutputsRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :page_size, :int32, 3, json_name: "pageSize"
    end
    add_message "indent.v1.ListOutputsResponse" do
      optional :space_name, :string, 1, json_name: "spaceName"
      repeated :outputs, :message, 2, "indent.v1.Output", json_name: "outputs"
    end
    add_message "indent.v1.GetOutputRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :output_name, :string, 3, json_name: "outputName"
    end
    add_message "indent.v1.CreateOutputRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :output, :message, 3, "indent.v1.Output", json_name: "output"
    end
    add_message "indent.v1.UpdateOutputRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :output_name, :string, 3, json_name: "outputName"
      optional :output, :message, 4, "indent.v1.Output", json_name: "output"
    end
    add_message "indent.v1.DeleteOutputRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :output_name, :string, 3, json_name: "outputName"
    end
    add_message "indent.v1.Output" do
      optional :name, :string, 1, json_name: "name"
      optional :display_name, :string, 2, json_name: "displayName"
      optional :schema, :message, 3, "indent.v1.Schema", json_name: "schema"
      optional :storage, :message, 4, "indent.v1.Storage", json_name: "storage"
    end
    add_message "indent.v1.ListCredentialsRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :page_size, :int32, 3, json_name: "pageSize"
    end
    add_message "indent.v1.ListCredentialsResponse" do
      repeated :credentials, :message, 1, "indent.v1.Credential", json_name: "credentials"
    end
    add_message "indent.v1.CreateCredentialRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :credential, :message, 3, "indent.v1.Credential", json_name: "credential"
    end
    add_message "indent.v1.DeleteCredentialRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :provider_name, :string, 2, json_name: "providerName"
      optional :credential_name, :string, 3, json_name: "credentialName"
    end
  end
end

module Indent
  module V1
    ListProvidersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListProvidersRequest").msgclass
    ListProvidersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListProvidersResponse").msgclass
    GetProviderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetProviderRequest").msgclass
    CreateProviderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateProviderRequest").msgclass
    UpdateProviderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdateProviderRequest").msgclass
    DeleteProviderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteProviderRequest").msgclass
    Provider = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Provider").msgclass
    ListInputsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListInputsRequest").msgclass
    ListInputsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListInputsResponse").msgclass
    GetInputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetInputRequest").msgclass
    CreateInputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateInputRequest").msgclass
    UpdateInputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdateInputRequest").msgclass
    DeleteInputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteInputRequest").msgclass
    Input = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Input").msgclass
    ListOutputsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListOutputsRequest").msgclass
    ListOutputsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListOutputsResponse").msgclass
    GetOutputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetOutputRequest").msgclass
    CreateOutputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateOutputRequest").msgclass
    UpdateOutputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdateOutputRequest").msgclass
    DeleteOutputRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteOutputRequest").msgclass
    Output = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Output").msgclass
    ListCredentialsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListCredentialsRequest").msgclass
    ListCredentialsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListCredentialsResponse").msgclass
    CreateCredentialRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateCredentialRequest").msgclass
    DeleteCredentialRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteCredentialRequest").msgclass
  end
end
