# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indent/v1/resource_api.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/rpc/status_pb'
require 'indent/audit/v1/resources_pb'
require 'indent/v1/resources_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("indent/v1/resource_api.proto", :syntax => :proto3) do
    add_message "indent.v1.ListResourcesRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :label_selector, :string, 2, json_name: "labelSelector"
      optional :latest, :bool, 3, json_name: "latest"
      repeated :among, :string, 4, json_name: "among"
      optional :view, :string, 5, json_name: "view"
      optional :page_size, :int32, 10, json_name: "pageSize"
      optional :page_token, :string, 11, json_name: "pageToken"
    end
    add_message "indent.v1.ListResourcesResponse" do
      repeated :resources, :message, 1, "indent.audit.v1.Resource", json_name: "resources"
      optional :next_page_token, :string, 2, json_name: "nextPageToken"
    end
    add_message "indent.v1.GetResourceRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :resource_name, :string, 2, json_name: "resourceName"
    end
    add_message "indent.v1.CreateResourceRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :ephemeral, :bool, 5, json_name: "ephemeral"
      optional :resource, :message, 40, "indent.audit.v1.Resource", json_name: "resource"
    end
    add_message "indent.v1.UpdateResourceRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :resource_name, :string, 3, json_name: "resourceName"
      optional :ephemeral, :bool, 5, json_name: "ephemeral"
      optional :resource, :message, 40, "indent.audit.v1.Resource", json_name: "resource"
    end
    add_message "indent.v1.DeleteResourceRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :resource_name, :string, 2, json_name: "resourceName"
    end
    add_message "indent.v1.BulkDeleteRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      repeated :resource_names, :string, 40, json_name: "resourceNames"
    end
    add_message "indent.v1.BulkDeleteResponse" do
    end
    add_message "indent.v1.BulkUpdateRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      repeated :resources, :message, 40, "indent.audit.v1.Resource", json_name: "resources"
    end
    add_message "indent.v1.BulkUpdateResponse" do
      repeated :resources, :message, 5, "indent.audit.v1.Resource", json_name: "resources"
    end
    add_message "indent.v1.PullUpdateRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      repeated :kinds, :string, 40, json_name: "kinds"
      map :flags, :string, :string, 60
    end
    add_message "indent.v1.PullUpdateResponse" do
      repeated :resources, :message, 5, "indent.audit.v1.Resource", json_name: "resources"
      optional :status, :message, 6, "google.rpc.Status", json_name: "status"
    end
    add_message "indent.v1.ApplyUpdateResponse" do
      optional :status, :message, 1, "google.rpc.Status", json_name: "status"
    end
    add_message "indent.v1.GetDecisionResponse" do
      optional :status, :message, 1, "google.rpc.Status", json_name: "status"
      repeated :claims, :message, 10, "indent.audit.v1.Event", json_name: "claims"
    end
    add_message "indent.v1.ListResourcePoliciesRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      repeated :among, :string, 4, json_name: "among"
      optional :label_selector, :string, 5, json_name: "labelSelector"
      optional :page_size, :int32, 10, json_name: "pageSize"
      optional :page_token, :string, 11, json_name: "pageToken"
    end
    add_message "indent.v1.ListResourcePoliciesResponse" do
      repeated :policies, :message, 1, "indent.v1.ResourcePolicy", json_name: "policies"
      optional :next_page_token, :string, 5, json_name: "nextPageToken"
    end
    add_message "indent.v1.GetResourcePolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :policy_name, :string, 2, json_name: "policyName"
    end
    add_message "indent.v1.CreateResourcePolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :policy, :message, 40, "indent.v1.ResourcePolicy", json_name: "policy"
    end
    add_message "indent.v1.UpdateResourcePolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :policy_name, :string, 3, json_name: "policyName"
      optional :policy, :message, 40, "indent.v1.ResourcePolicy", json_name: "policy"
    end
    add_message "indent.v1.DeleteResourcePolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :policy_name, :string, 2, json_name: "policyName"
    end
    add_message "indent.v1.TestResourcePolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :view, :string, 5, json_name: "view"
      repeated :policies, :message, 40, "indent.v1.ResourcePolicy", json_name: "policies"
    end
    add_message "indent.v1.TestResourcePolicyResponse" do
      repeated :resources, :message, 1, "indent.audit.v1.Resource", json_name: "resources"
    end
    add_message "indent.v1.ResourcePolicy" do
      optional :meta, :message, 5, "indent.audit.v1.Meta", json_name: "meta"
      optional :base, :message, 15, "indent.v1.PolicyBase", json_name: "base"
    end
    add_message "indent.v1.ListPullPoliciesResponse" do
      repeated :policies, :message, 1, "indent.v1.PullUpdatePolicy", json_name: "policies"
      optional :next_page_token, :string, 5, json_name: "nextPageToken"
    end
    add_message "indent.v1.CreatePullPolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :policy, :message, 40, "indent.v1.PullUpdatePolicy", json_name: "policy"
    end
    add_message "indent.v1.UpdatePullPolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :policy_name, :string, 3, json_name: "policyName"
      optional :policy, :message, 40, "indent.v1.PullUpdatePolicy", json_name: "policy"
    end
    add_message "indent.v1.PullUpdatePolicy" do
      optional :meta, :message, 5, "indent.audit.v1.Meta", json_name: "meta"
      optional :base, :message, 15, "indent.v1.PolicyBase", json_name: "base"
      optional :schedule, :string, 20, json_name: "schedule"
      repeated :kinds, :string, 40, json_name: "kinds"
      map :flags, :string, :string, 60
    end
  end
end

module Indent
  module V1
    ListResourcesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListResourcesRequest").msgclass
    ListResourcesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListResourcesResponse").msgclass
    GetResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetResourceRequest").msgclass
    CreateResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateResourceRequest").msgclass
    UpdateResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdateResourceRequest").msgclass
    DeleteResourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteResourceRequest").msgclass
    BulkDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.BulkDeleteRequest").msgclass
    BulkDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.BulkDeleteResponse").msgclass
    BulkUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.BulkUpdateRequest").msgclass
    BulkUpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.BulkUpdateResponse").msgclass
    PullUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.PullUpdateRequest").msgclass
    PullUpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.PullUpdateResponse").msgclass
    ApplyUpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ApplyUpdateResponse").msgclass
    GetDecisionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetDecisionResponse").msgclass
    ListResourcePoliciesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListResourcePoliciesRequest").msgclass
    ListResourcePoliciesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListResourcePoliciesResponse").msgclass
    GetResourcePolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetResourcePolicyRequest").msgclass
    CreateResourcePolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateResourcePolicyRequest").msgclass
    UpdateResourcePolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdateResourcePolicyRequest").msgclass
    DeleteResourcePolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteResourcePolicyRequest").msgclass
    TestResourcePolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.TestResourcePolicyRequest").msgclass
    TestResourcePolicyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.TestResourcePolicyResponse").msgclass
    ResourcePolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ResourcePolicy").msgclass
    ListPullPoliciesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListPullPoliciesResponse").msgclass
    CreatePullPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreatePullPolicyRequest").msgclass
    UpdatePullPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdatePullPolicyRequest").msgclass
    PullUpdatePolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.PullUpdatePolicy").msgclass
  end
end
