# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: indent/v1/resource_api.proto for package 'indent.v1'
# Original file comments:
#
# Copyright 2019 Indent Inc
#
#

require 'grpc'
require 'indent/v1/resource_api_pb'

module Indent
  module V1
    module ResourceAPI
      # ResourceAPI contains the resources associated with managing and evaluating resources.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'indent.v1.ResourceAPI'

        # List the Resources in the given space.
        rpc :ListResources, ::Indent::V1::ListResourcesRequest, ::Indent::V1::ListResourcesResponse
        # Retrieve specified Resource by name and Space.
        rpc :GetResource, ::Indent::V1::GetResourceRequest, ::Indent::Audit::V1::Resource
        # Create a new Resource within a space.
        rpc :CreateResource, ::Indent::V1::CreateResourceRequest, ::Indent::Audit::V1::Resource
        # UpdateResource allows modification of the contents of a Resource.
        rpc :UpdateResource, ::Indent::V1::UpdateResourceRequest, ::Indent::Audit::V1::Resource
        # Permanently destroy a Resource.
        rpc :DeleteResource, ::Indent::V1::DeleteResourceRequest, ::Indent::Audit::V1::Resource
        # Permanently bulk destroy Resources.
        rpc :BulkDelete, ::Indent::V1::BulkDeleteRequest, ::Indent::V1::BulkDeleteResponse
        # BulkUpdate allows multiple resources to be created or updated at the same time.
        rpc :BulkUpdate, ::Indent::V1::BulkUpdateRequest, ::Indent::V1::BulkUpdateResponse
        # PullUpdate retrieves information about the specified kinds and merges them into Resources.
        rpc :PullUpdate, ::Indent::V1::PullUpdateRequest, ::Indent::V1::PullUpdateResponse
        # List the ResourcePolicies in the given space.
        rpc :ListPolicies, ::Indent::V1::ListResourcePoliciesRequest, ::Indent::V1::ListResourcePoliciesResponse
        # Retrieve specified ResourcePolicy by name and Space.
        rpc :GetPolicy, ::Indent::V1::GetResourcePolicyRequest, ::Indent::V1::ResourcePolicy
        # Create a new ResourcePolicy within a space.
        rpc :CreatePolicy, ::Indent::V1::CreateResourcePolicyRequest, ::Indent::V1::ResourcePolicy
        # Update an existing ResourcePolicy.
        rpc :UpdatePolicy, ::Indent::V1::UpdateResourcePolicyRequest, ::Indent::V1::ResourcePolicy
        # Permanently destroy a ResourcePolicy.
        rpc :DeletePolicy, ::Indent::V1::DeleteResourcePolicyRequest, ::Indent::V1::ResourcePolicy
        # Test how ResourcePolicies apply to Resources.
        rpc :TestPolicy, ::Indent::V1::TestResourcePolicyRequest, ::Indent::V1::TestResourcePolicyResponse
        # List the PullUpdatePolicies in the given space.
        rpc :ListPullPolicies, ::Indent::V1::ListResourcePoliciesRequest, ::Indent::V1::ListPullPoliciesResponse
        # Retrieve specified PullUpdatePolicy by name and Space.
        rpc :GetPullPolicy, ::Indent::V1::GetResourcePolicyRequest, ::Indent::V1::PullUpdatePolicy
        # Create a new PullUpdatePolicy within a space.
        rpc :CreatePullPolicy, ::Indent::V1::CreatePullPolicyRequest, ::Indent::V1::PullUpdatePolicy
        # Update an existing PullUpdatePolicy.
        rpc :UpdatePullPolicy, ::Indent::V1::UpdatePullPolicyRequest, ::Indent::V1::PullUpdatePolicy
        # Permanently destroy a PullUpdatePolicy.
        rpc :DeletePullPolicy, ::Indent::V1::DeleteResourcePolicyRequest, ::Indent::V1::PullUpdatePolicy
      end

      Stub = Service.rpc_stub_class
    end
  end
end
