# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indent/v1/task_api.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'indent/audit/v1/resources_pb'
require 'indent/v1/resources_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("indent/v1/task_api.proto", :syntax => :proto3) do
    add_message "indent.v1.ListTasksRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :page_size, :int32, 2, json_name: "pageSize"
      repeated :among, :string, 4, json_name: "among"
    end
    add_message "indent.v1.ListTasksResponse" do
      repeated :tasks, :message, 1, "indent.v1.Task", json_name: "tasks"
    end
    add_message "indent.v1.GetTaskRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :task_name, :string, 5, json_name: "taskName"
    end
    add_message "indent.v1.CreateTaskRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :task, :message, 5, "indent.v1.Task", json_name: "task"
    end
    add_message "indent.v1.UpdateTaskRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :task_name, :string, 5, json_name: "taskName"
      optional :task, :message, 10, "indent.v1.Task", json_name: "task"
    end
    add_message "indent.v1.DeleteTaskRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :task_name, :string, 5, json_name: "taskName"
    end
    add_message "indent.v1.TaskPetitionDetails" do
      optional :scope, :string, 1, json_name: "scope"
      optional :petitionID, :string, 2, json_name: "petitionID"
    end
    add_message "indent.v1.Task" do
      optional :name, :string, 1, json_name: "name"
      optional :space_name, :string, 5, json_name: "spaceName"
      optional :meta, :message, 15, "indent.audit.v1.Meta", json_name: "meta"
      optional :display_name, :string, 20, json_name: "displayName"
      optional :description, :string, 25, json_name: "description"
      optional :assignee, :message, 30, "indent.audit.v1.Resource", json_name: "assignee"
      optional :phase, :enum, 35, "indent.v1.Task.Phase", json_name: "phase"
      optional :form, :message, 40, "indent.v1.Form", json_name: "form"
      oneof :details do
        optional :petition_details, :message, 45, "indent.v1.TaskPetitionDetails", json_name: "petitionDetails"
      end
    end
    add_enum "indent.v1.Task.Phase" do
      value :UNKNOWN, 0
      value :OPEN, 1
      value :CLOSED, 2
      value :DONE, 3
    end
  end
end

module Indent
  module V1
    ListTasksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListTasksRequest").msgclass
    ListTasksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListTasksResponse").msgclass
    GetTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetTaskRequest").msgclass
    CreateTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateTaskRequest").msgclass
    UpdateTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdateTaskRequest").msgclass
    DeleteTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteTaskRequest").msgclass
    TaskPetitionDetails = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.TaskPetitionDetails").msgclass
    Task = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Task").msgclass
    Task::Phase = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Task.Phase").enummodule
  end
end
