# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indent/v1/webhook_api.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'indent/audit/v1/resources_pb'
require 'indent/v1/resources_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("indent/v1/webhook_api.proto", :syntax => :proto3) do
    add_message "indent.v1.ListWebhooksRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      repeated :among, :string, 4, json_name: "among"
      optional :page_size, :int32, 10, json_name: "pageSize"
      optional :page_token, :string, 15, json_name: "pageToken"
    end
    add_message "indent.v1.ListWebhooksResponse" do
      repeated :webhooks, :message, 1, "indent.v1.Webhook", json_name: "webhooks"
      optional :next_page_token, :string, 2, json_name: "nextPageToken"
    end
    add_message "indent.v1.GetWebhookRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :webhook_name, :string, 5, json_name: "webhookName"
    end
    add_message "indent.v1.CreateWebhookRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :webhook, :message, 5, "indent.v1.Webhook", json_name: "webhook"
    end
    add_message "indent.v1.UpdateWebhookRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :webhook_name, :string, 5, json_name: "webhookName"
      optional :webhook, :message, 10, "indent.v1.Webhook", json_name: "webhook"
    end
    add_message "indent.v1.DeleteWebhookRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :webhook_name, :string, 5, json_name: "webhookName"
    end
    add_message "indent.v1.Webhook" do
      optional :name, :string, 1, json_name: "name"
      optional :space_name, :string, 2, json_name: "spaceName"
      optional :display_name, :string, 3, json_name: "displayName"
      map :labels, :string, :string, 5
      optional :url, :string, 10, json_name: "url"
      optional :method, :string, 20, json_name: "method"
      map :headers, :string, :message, 30, "indent.v1.Header"
      optional :secret, :string, 40, json_name: "secret"
      optional :dry_run, :bool, 50, json_name: "dryRun"
    end
    add_message "indent.v1.Header" do
      optional :credential, :string, 10, json_name: "credential"
      optional :value, :string, 20, json_name: "value"
    end
    add_message "indent.v1.ListWebhookPoliciesRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      repeated :among, :string, 4, json_name: "among"
      optional :label_selector, :string, 5, json_name: "labelSelector"
      optional :page_size, :int32, 10, json_name: "pageSize"
      optional :page_token, :string, 11, json_name: "pageToken"
    end
    add_message "indent.v1.ListWebhookPoliciesResponse" do
      repeated :policies, :message, 1, "indent.v1.WebhookPolicy", json_name: "policies"
      optional :next_page_token, :string, 5, json_name: "nextPageToken"
    end
    add_message "indent.v1.GetWebhookPolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :policy_name, :string, 2, json_name: "policyName"
    end
    add_message "indent.v1.CreateWebhookPolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :policy, :message, 40, "indent.v1.WebhookPolicy", json_name: "policy"
    end
    add_message "indent.v1.UpdateWebhookPolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :policy_name, :string, 3, json_name: "policyName"
      optional :policy, :message, 40, "indent.v1.WebhookPolicy", json_name: "policy"
    end
    add_message "indent.v1.DeleteWebhookPolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :policy_name, :string, 2, json_name: "policyName"
    end
    add_message "indent.v1.TestWebhookPolicyRequest" do
      optional :space_name, :string, 1, json_name: "spaceName"
      optional :view, :string, 5, json_name: "view"
      repeated :policies, :message, 40, "indent.v1.WebhookPolicy", json_name: "policies"
    end
    add_message "indent.v1.TestWebhookPolicyResponse" do
      repeated :webhooks, :message, 1, "indent.v1.Webhook", json_name: "webhooks"
    end
    add_message "indent.v1.WebhookPolicy" do
      optional :meta, :message, 5, "indent.audit.v1.Meta", json_name: "meta"
      optional :base, :message, 15, "indent.v1.PolicyBase", json_name: "base"
      repeated :webhooks, :message, 25, "indent.v1.WebhookIdentifier", json_name: "webhooks"
    end
    add_message "indent.v1.WebhookIdentifier" do
      optional :name, :string, 10, json_name: "name"
    end
  end
end

module Indent
  module V1
    ListWebhooksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListWebhooksRequest").msgclass
    ListWebhooksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListWebhooksResponse").msgclass
    GetWebhookRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetWebhookRequest").msgclass
    CreateWebhookRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateWebhookRequest").msgclass
    UpdateWebhookRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdateWebhookRequest").msgclass
    DeleteWebhookRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteWebhookRequest").msgclass
    Webhook = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Webhook").msgclass
    Header = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.Header").msgclass
    ListWebhookPoliciesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListWebhookPoliciesRequest").msgclass
    ListWebhookPoliciesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.ListWebhookPoliciesResponse").msgclass
    GetWebhookPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.GetWebhookPolicyRequest").msgclass
    CreateWebhookPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.CreateWebhookPolicyRequest").msgclass
    UpdateWebhookPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.UpdateWebhookPolicyRequest").msgclass
    DeleteWebhookPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.DeleteWebhookPolicyRequest").msgclass
    TestWebhookPolicyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.TestWebhookPolicyRequest").msgclass
    TestWebhookPolicyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.TestWebhookPolicyResponse").msgclass
    WebhookPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.WebhookPolicy").msgclass
    WebhookIdentifier = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.v1.WebhookIdentifier").msgclass
  end
end
