# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indent/log/example.proto

require 'google/protobuf'

require 'indent/log/log_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("indent/log/example.proto", :syntax => :proto3) do
    add_message "indent.log.SimpleMessage" do
      optional :string_value, :string, 1, json_name: "stringValue"
      optional :bool_value, :bool, 2, json_name: "boolValue"
    end
    add_message "indent.log.NotLoggingSimpleMessage" do
      optional :string_value, :string, 1, json_name: "stringValue"
      optional :bool_value, :bool, 2, json_name: "boolValue"
    end
    add_message "indent.log.NumberMessage" do
      optional :float_value, :float, 1, json_name: "floatValue"
      optional :double_value, :double, 2, json_name: "doubleValue"
      optional :int32_value, :int32, 3, json_name: "int32Value"
      optional :int64_value, :int64, 4, json_name: "int64Value"
      optional :uint32_value, :uint32, 5, json_name: "uint32Value"
      optional :uint64_value, :uint64, 6, json_name: "uint64Value"
      optional :sint32_value, :sint32, 7, json_name: "sint32Value"
      optional :sint64_value, :sint64, 8, json_name: "sint64Value"
      optional :fixed32_value, :fixed32, 9, json_name: "fixed32Value"
      optional :fixed64_value, :fixed64, 10, json_name: "fixed64Value"
      optional :sfixed32_value, :sfixed32, 11, json_name: "sfixed32Value"
      optional :sfixed64_value, :sfixed64, 12, json_name: "sfixed64Value"
    end
    add_message "indent.log.NotLoggingNumberMessage" do
      optional :float_value, :float, 1, json_name: "floatValue"
      optional :double_value, :double, 2, json_name: "doubleValue"
      optional :int32_value, :int32, 3, json_name: "int32Value"
      optional :int64_value, :int64, 4, json_name: "int64Value"
      optional :uint32_value, :uint32, 5, json_name: "uint32Value"
      optional :uint64_value, :uint64, 6, json_name: "uint64Value"
      optional :sint32_value, :sint32, 7, json_name: "sint32Value"
      optional :sint64_value, :sint64, 8, json_name: "sint64Value"
      optional :fixed32_value, :fixed32, 9, json_name: "fixed32Value"
      optional :fixed64_value, :fixed64, 10, json_name: "fixed64Value"
      optional :sfixed32_value, :sfixed32, 11, json_name: "sfixed32Value"
      optional :sfixed64_value, :sfixed64, 12, json_name: "sfixed64Value"
    end
    add_message "indent.log.RepeatedNumberMessage" do
      repeated :float_values, :float, 1, json_name: "floatValues"
      repeated :double_values, :double, 2, json_name: "doubleValues"
      repeated :int32_values, :int32, 3, json_name: "int32Values"
      repeated :int64_values, :int64, 4, json_name: "int64Values"
      repeated :uint32_values, :uint32, 5, json_name: "uint32Values"
      repeated :uint64_values, :uint64, 6, json_name: "uint64Values"
      repeated :sint32_values, :sint32, 7, json_name: "sint32Values"
      repeated :sint64_values, :sint64, 8, json_name: "sint64Values"
      repeated :fixed32_values, :fixed32, 9, json_name: "fixed32Values"
      repeated :fixed64_values, :fixed64, 10, json_name: "fixed64Values"
      repeated :sfixed32_values, :sfixed32, 11, json_name: "sfixed32Values"
      repeated :sfixed64_values, :sfixed64, 12, json_name: "sfixed64Values"
    end
    add_message "indent.log.NotLoggingRepeatedNumberMessage" do
      repeated :float_values, :float, 1, json_name: "floatValues"
      repeated :double_values, :double, 2, json_name: "doubleValues"
      repeated :int32_values, :int32, 3, json_name: "int32Values"
      repeated :int64_values, :int64, 4, json_name: "int64Values"
      repeated :uint32_values, :uint32, 5, json_name: "uint32Values"
      repeated :uint64_values, :uint64, 6, json_name: "uint64Values"
      repeated :sint32_values, :sint32, 7, json_name: "sint32Values"
      repeated :sint64_values, :sint64, 8, json_name: "sint64Values"
      repeated :fixed32_values, :fixed32, 9, json_name: "fixed32Values"
      repeated :fixed64_values, :fixed64, 10, json_name: "fixed64Values"
      repeated :sfixed32_values, :sfixed32, 11, json_name: "sfixed32Values"
      repeated :sfixed64_values, :sfixed64, 12, json_name: "sfixed64Values"
    end
    add_message "indent.log.NestedMessage" do
      optional :nested_value, :message, 1, "indent.log.NestedMessage.Nested", json_name: "nestedValue"
      repeated :repeated_nested_values, :message, 2, "indent.log.NestedMessage.Nested", json_name: "repeatedNestedValues"
    end
    add_message "indent.log.NestedMessage.Nested" do
      optional :int32_value, :int32, 1, json_name: "int32Value"
      optional :string_value, :string, 2, json_name: "stringValue"
    end
    add_message "indent.log.NotLoggingNestedMessage" do
      optional :nested_value, :message, 1, "indent.log.NotLoggingNestedMessage.Nested", json_name: "nestedValue"
      repeated :repeated_nested_values, :message, 2, "indent.log.NotLoggingNestedMessage.Nested", json_name: "repeatedNestedValues"
    end
    add_message "indent.log.NotLoggingNestedMessage.Nested" do
      optional :int32_value, :int32, 1, json_name: "int32Value"
      optional :string_value, :string, 2, json_name: "stringValue"
    end
    add_message "indent.log.EnumMessage" do
      optional :numeric_enum_value, :enum, 1, "indent.log.NumericEnum", json_name: "numericEnumValue"
      repeated :repeated_numeric_enum_values, :enum, 2, "indent.log.NumericEnum", json_name: "repeatedNumericEnumValues"
      optional :aliased_enum_value, :enum, 3, "indent.log.AliasedEnum", json_name: "aliasedEnumValue"
      optional :nested_enum_value, :enum, 4, "indent.log.EnumMessage.Nested", json_name: "nestedEnumValue"
      repeated :repeated_nested_enum_values, :enum, 5, "indent.log.EnumMessage.Nested", json_name: "repeatedNestedEnumValues"
    end
    add_enum "indent.log.EnumMessage.Nested" do
      value :UNKNOWN, 0
      value :PENDING, 1
      value :COMPLETED, 2
    end
    add_message "indent.log.NotLoggingEnumMessage" do
      optional :numeric_enum_value, :enum, 1, "indent.log.NumericEnum", json_name: "numericEnumValue"
      repeated :repeated_numeric_enum_values, :enum, 2, "indent.log.NumericEnum", json_name: "repeatedNumericEnumValues"
      optional :aliased_enum_value, :enum, 3, "indent.log.AliasedEnum", json_name: "aliasedEnumValue"
      optional :nested_enum_value, :enum, 4, "indent.log.NotLoggingEnumMessage.Nested", json_name: "nestedEnumValue"
      repeated :repeated_nested_enum_values, :enum, 5, "indent.log.NotLoggingEnumMessage.Nested", json_name: "repeatedNestedEnumValues"
    end
    add_enum "indent.log.NotLoggingEnumMessage.Nested" do
      value :UNKNOWN, 0
      value :PENDING, 1
      value :COMPLETED, 2
    end
    add_message "indent.log.Oneof" do
      oneof :oneof_value do
        optional :int32_value, :int32, 1, json_name: "int32Value"
        optional :string_value, :string, 2, json_name: "stringValue"
      end
    end
    add_message "indent.log.OneofMessage" do
      repeated :repeated_oneof_values, :message, 3, "indent.log.Oneof", json_name: "repeatedOneofValues"
      oneof :oneof_value do
        optional :int32_value, :int32, 1, json_name: "int32Value"
        optional :string_value, :string, 2, json_name: "stringValue"
      end
    end
    add_message "indent.log.NotLoggingOneofMessage" do
      repeated :repeated_oneof_values, :message, 3, "indent.log.Oneof", json_name: "repeatedOneofValues"
      oneof :oneof_value do
        optional :int32_value, :int32, 1, json_name: "int32Value"
        optional :string_value, :string, 2, json_name: "stringValue"
      end
    end
    add_message "indent.log.MapMessage" do
      map :mapped_value, :int32, :string, 1
      map :mapped_enum_value, :string, :enum, 2, "indent.log.NumericEnum"
      map :mapped_nested_value, :string, :message, 3, "indent.log.NestedMessage"
    end
    add_message "indent.log.NotLoggingMapMessage" do
      map :mapped_value, :int32, :string, 1
      map :mapped_enum_value, :string, :enum, 2, "indent.log.NumericEnum"
      map :mapped_nested_value, :string, :message, 3, "indent.log.NestedMessage"
    end
    add_message "indent.log.JsonNameOptionMessage" do
      optional :string_value, :string, 1, json_name: "renamed_value"
    end
    add_message "indent.log.NotLoggingJsonNameOptionMessage" do
      optional :string_value, :string, 1, json_name: "renamed_value"
    end
    add_message "indent.log.WellKnownTypeMessage" do
      optional :duration, :message, 1, "google.protobuf.Duration", json_name: "duration"
      optional :timestamp, :message, 2, "google.protobuf.Timestamp", json_name: "timestamp"
    end
    add_message "indent.log.NotLoggingWellKnownTypeMessage" do
      optional :duration, :message, 1, "google.protobuf.Duration", json_name: "duration"
      optional :timestamp, :message, 2, "google.protobuf.Timestamp", json_name: "timestamp"
    end
    add_message "indent.log.MixedLoggingMessage" do
      optional :string_value, :string, 1, json_name: "stringValue"
      optional :bool_value, :bool, 2, json_name: "boolValue"
      optional :int32_value, :int32, 3, json_name: "int32Value"
    end
    add_enum "indent.log.NumericEnum" do
      value :ZERO, 0
      value :ONE, 1
      value :TWO, 2
    end
    add_enum "indent.log.AliasedEnum" do
      value :UNKNOWN, 0
      value :STARTED, 1
      value :RUNNING, 1
    end
  end
end

module Indent
  module Log
    SimpleMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.SimpleMessage").msgclass
    NotLoggingSimpleMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingSimpleMessage").msgclass
    NumberMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NumberMessage").msgclass
    NotLoggingNumberMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingNumberMessage").msgclass
    RepeatedNumberMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.RepeatedNumberMessage").msgclass
    NotLoggingRepeatedNumberMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingRepeatedNumberMessage").msgclass
    NestedMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NestedMessage").msgclass
    NestedMessage::Nested = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NestedMessage.Nested").msgclass
    NotLoggingNestedMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingNestedMessage").msgclass
    NotLoggingNestedMessage::Nested = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingNestedMessage.Nested").msgclass
    EnumMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.EnumMessage").msgclass
    EnumMessage::Nested = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.EnumMessage.Nested").enummodule
    NotLoggingEnumMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingEnumMessage").msgclass
    NotLoggingEnumMessage::Nested = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingEnumMessage.Nested").enummodule
    Oneof = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.Oneof").msgclass
    OneofMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.OneofMessage").msgclass
    NotLoggingOneofMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingOneofMessage").msgclass
    MapMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.MapMessage").msgclass
    NotLoggingMapMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingMapMessage").msgclass
    JsonNameOptionMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.JsonNameOptionMessage").msgclass
    NotLoggingJsonNameOptionMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingJsonNameOptionMessage").msgclass
    WellKnownTypeMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.WellKnownTypeMessage").msgclass
    NotLoggingWellKnownTypeMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NotLoggingWellKnownTypeMessage").msgclass
    MixedLoggingMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.MixedLoggingMessage").msgclass
    NumericEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.NumericEnum").enummodule
    AliasedEnum = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("indent.log.AliasedEnum").enummodule
  end
end
