# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indent/log/log.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("indent/log/log.proto", :syntax => :proto3) do
  end
end

module Indent
  module Log
  end
end
