# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: indent/audit/v1/audit_api.proto for package 'indent.audit.v1'
# Original file comments:
#
# Copyright 2019 Indent Inc
#
#

require 'grpc'
require 'indent/audit/v1/audit_api_pb'

module Indent
  module Audit
    module V1
      module AuditAPI
        # AuditAPI collects Audit Events from external Inputs.
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'indent.audit.v1.AuditAPI'

          # Write a new Event to a Target.
          rpc :Write, ::Indent::Audit::V1::WriteRequest, ::Google::Protobuf::Empty
          # WriteEvent a new Event into Indent.
          #
          # Deprecated: Use Write.
          rpc :WriteEvent, ::Indent::Audit::V1::WriteEventRequest, ::Google::Protobuf::Empty
          # WriteBatch writes multiple Events into Indent.
          #
          # Deprecated: Use Write.
          rpc :WriteBatch, ::Indent::Audit::V1::WriteBatchRequest, ::Google::Protobuf::Empty
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
